### ISSUE TITLE
the program worked very well, but where to find the mp3 resource and screen files?

### ISSUE THREAD

**Issue by vvlaw** [sarajaksa/subtitles2anki#4]
Hello, sarajaksa.

the program worked well, but i dont know where are the mp3 and jpg files?

Ok so we went to the beach	[sound:0_0_2.340_1.mp3]	<img src='0_0_2.340_1.jpg'>

thanks in advance

**Comment by sarajaksa** [comment]
Can I ask how do you run this program?

The reason that I am asking is, that the files are generated in the folder from which you run your program. So finding out how you run it could help with the debugging. But would also be the same folder then the one with the CSV, and I am guessing based on you comment, that you managed to find that one.

I also added the additional parameter in the script, so if you call the new version now with the `--folder <folder name>`, it would save you the files in the right place.

**Comment by vvlaw** [comment]
Hi, Sarajaksa.

 python3 subtitles2anki.py -v 1.mp4 -s 1.srt --folder /home/vvlaw/subtitles2anki   
1
2
3
4
5

the “Anki.csv” can created very well. but still has no [sound:0_0_20.660_11.mp3] and <img src='0_0_20.660_11.jpg'>

in the /home/vvlaw/subtitiles2anki

Thanks

**Comment by sarajaksa** [comment]
Would you be willing to share the subtitle file with me? If you do not want to share it publicly, you can send it to my emails (like sarajaksa@gmail.com ). Maybe I did not account some specific formatting, that could also be a part of srt file. 

The only other things that I could think of do not really make sense. Like, maybe the files are not created, because the ffmpeg is not installed (but then it should not run at all), or that the video file is shorter than the first line of subtitles.

The only other thing that I can think of is, that I am not understanding the problem. But not sure what kind of information am I missing...

**Comment by sarajaksa** [comment]
The issue ended up being the Python under the miniconda. Once the conda was activated, the issue went away.

Before realizing this, I have suggested just not using the script to generate audio and images. One could use a command line like this to generate them:

```
cat 1.srt | grep ">" | awk '{print "ffmpeg \55ss " $1 " \55to " $3 " \55i 1.webm \55b:a 320K \55vn " NR ".mp3"}' | sed "s/,/\./g" | sed "s/\r//g"
```

The CSV for Anki cards can still be done with the script, but in this case the name of files generated would need to change (line 158 and 159):

```
audio = str(position) + ".mp3"
picture = str(position) + ".jpg"
```
